import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { ArrowRight, ExternalLink, Newspaper } from "lucide-react";
import { StructuredData } from "@/components/StructuredData";
import { buildGraph } from "@/lib/structured-data";
import { site } from "@/lib/site";
import styles from "./page.module.css";

const title = "House Extension Planning Permission in Birmingham: 2026 Guide";
const description = "Do you need planning permission for a house extension in Birmingham? Understand permitted development, rear and side extension rules, prior approval and the application process.";
const schemaDescription = "A practical guide to planning permission, permitted development, prior approval and Lawful Development Certificates for Birmingham house extensions.";
const path = "/journal/house-extension-planning-permission-birmingham-2026-guide";
const url = `${site.url}${path}`;
const image = `${site.url}/images/selected-work-2.webp`;
const publicationDate = "2026-08-02";

const faqs = [
  { question: "How far can I extend without planning permission in Birmingham?", answer: "A qualifying single-storey rear extension may extend up to 4 metres from the original rear wall of a detached house or up to 3 metres for another house under the standard permitted-development limits. Larger extensions may sometimes use the prior-approval process, up to 8 metres for detached houses and 6 metres for other houses. These dimensions are only part of the rules, and the property and complete proposal must be assessed." },
  { question: "Can I build a six-metre rear extension in Birmingham?", answer: "A qualifying single-storey rear extension of up to 6 metres may potentially use the larger-home-extension prior-approval process for a house that is not detached. It must satisfy the other relevant permitted-development requirements, and the council must complete the neighbour-consultation process before authorised work begins." },
  { question: "Can I build an eight-metre extension on a detached house?", answer: "A qualifying detached house may potentially use the larger-home-extension procedure for a single-storey rear extension extending more than 4 metres and no more than 8 metres from the original rear wall. Other permitted-development limitations and conditions still apply." },
  { question: "Do side extensions need planning permission in Birmingham?", answer: "Some single-storey side extensions may qualify as permitted development where they satisfy limitations relating to width, height, position and property status. Side extensions on designated land and larger or multi-storey proposals are more likely to require planning permission." },
  { question: "Does a two-storey extension require planning permission?", answer: "Many two-storey extensions require planning permission, although limited forms of two-storey rear extension may potentially qualify as permitted development. The rules are restrictive and should be assessed against the individual property before work is planned." },
  { question: "Do permitted-development rights apply to flats?", answer: "Householder permitted-development rights under Part 1 generally apply to dwellinghouses and not to flats or maisonettes. Alterations or extensions to a flat will normally require a planning assessment and may require planning permission." },
  { question: "What is a Lawful Development Certificate?", answer: "A Proposed Lawful Development Certificate is a formal council decision confirming whether proposed work would be lawful. It is not planning permission, but it can provide useful evidence that an extension complies with permitted-development legislation." },
  { question: "Can my neighbour stop my extension?", answer: "A neighbour does not directly decide an ordinary planning application. Birmingham City Council considers any relevant planning representations as part of its assessment. Under the larger-home-extension procedure, adjoining neighbours are consulted and the council may assess the proposal’s impact on residential amenity where concerns are raised." },
  { question: "Do I need Building Regulations approval if planning permission is not required?", answer: "Usually, yes. Planning and Building Regulations are separate systems. An extension may be permitted development while still requiring Building Regulations approval for matters such as structure, fire safety, insulation, ventilation and drainage." },
  { question: "Can Hepburn Architects guarantee planning permission?", answer: "No. Planning decisions are made by the local planning authority. Hepburn Architects can assess constraints, develop an appropriate design and prepare a coordinated submission, but planning permission cannot legitimately be guaranteed." },
] as const;

const contents = ["The four main approval routes", "What can sometimes be built under permitted development?", "What does ‘the original house’ mean?", "When permitted-development rights may not be available", "Conservation areas and Birmingham’s historic neighbourhoods", "How Birmingham City Council assesses an extension application", "Do the 45-degree rules apply in Birmingham?", "Planning permission, Building Regulations and the Party Wall Act", "What drawings are normally required?", "The house-extension planning process", "How long does a householder application take?", "Common reasons applications encounter difficulty", "How much does an extension planning application cost?", "Should I use an architect for a house extension?", "How Hepburn Architects supports Birmingham extension projects"] as const;
const slugify = (value: string) => value.toLowerCase().replace(/[‘’?]/g, "").replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");

export const metadata: Metadata = {
  title: { absolute: "House Extension Planning Permission Birmingham | 2026 Guide" }, description,
  alternates: { canonical: url },
  openGraph: { title: "House Extension Planning Permission Birmingham: 2026 Guide", description: "A practical guide to planning permission, permitted development and prior approval for house extensions in Birmingham.", url, type: "article", publishedTime: publicationDate, modifiedTime: publicationDate, authors: [`${site.url}/about`], images: [{ url: image, width: 1024, height: 485, alt: "House extension project in Birmingham designed by Hepburn Architects" }] },
  twitter: { card: "summary_large_image", title: "House Extension Planning Permission Birmingham: 2026 Guide", description: "A practical guide to planning permission, permitted development and prior approval for house extensions in Birmingham.", images: [image] },
};

export default function BirminghamExtensionPlanningGuidePage() {
  const schema = { "@context": "https://schema.org", "@graph": [
    { "@type": "BlogPosting", "@id": `${url}#article`, headline: title, description: schemaDescription, author: { "@id": `${site.url}/#david-hepburn` }, publisher: { "@id": `${site.url}/#organization` }, mainEntityOfPage: url, datePublished: publicationDate, dateModified: publicationDate, image: { "@type": "ImageObject", url: image, width: 1024, height: 485 }, articleSection: "Planning guidance", inLanguage: "en-GB" },
    { "@type": "WebPage", "@id": `${url}#webpage`, url, name: title, description: schemaDescription, isPartOf: { "@id": `${site.url}/#website` }, primaryImageOfPage: { "@id": `${url}#primaryimage` }, breadcrumb: { "@id": `${url}#breadcrumb` }, mainEntity: { "@id": `${url}#article` }, inLanguage: "en-GB" },
    { "@type": "ImageObject", "@id": `${url}#primaryimage`, url: image, width: 1024, height: 485 },
    { "@type": "BreadcrumbList", "@id": `${url}#breadcrumb`, itemListElement: [{ "@type": "ListItem", position: 1, name: "Home", item: `${site.url}/` }, { "@type": "ListItem", position: 2, name: "Journal", item: `${site.url}/blog` }, { "@type": "ListItem", position: 3, name: title, item: url }] },
    { "@type": "FAQPage", "@id": `${url}#faq`, mainEntity: faqs.map((faq) => ({ "@type": "Question", name: faq.question, acceptedAnswer: { "@type": "Answer", text: faq.answer } })) },
  ] };
  return <>
    <StructuredData data={buildGraph(schema)} />
    <article className={`section ${styles.article}`}><div className="shell article-page">
      <nav aria-label="Breadcrumb" className="muted small-copy"><Link href="/">Home</Link> · <Link href="/blog">Journal</Link></nav>
      <small className="eyebrow"><Newspaper size={14}/> Planning guidance</small><h1>{title}</h1>
      <p className="lead">Planning a rear, side or two-storey extension in Birmingham? This guide explains when planning permission may be required, what can sometimes be built under permitted development and how Birmingham City Council assesses householder proposals.</p>
      <p className={styles.byline}>Published 2 August 2026 · 10 minutes read · By <Link href="/about">David Hepburn</Link></p>
      <figure className={styles.hero}><Image src="/images/selected-work-2.webp" alt="Contemporary rear extension to a traditional family home" width={1448} height={1086} priority sizes="(max-width: 1100px) 100vw, 1100px"/><figcaption>A contemporary rear extension designed around family living and the garden.</figcaption></figure>
      <div className={styles.body}>
        <p>A house extension can transform how a Birmingham home works, but one of the first questions is usually:</p><aside className={styles.question}><strong>Do I need planning permission?</strong></aside>
        <p>The answer depends on much more than the extension’s floor area. The type of house, position of the extension, previous additions, planning history, conservation status, dimensions and relationship with neighbouring properties can all affect the approval route.</p><p>Some extensions require a householder planning application. Others may qualify as permitted development. Larger single-storey rear extensions can sometimes use a separate prior-approval process. Even where planning permission is not required, Building Regulations approval and other consents may still be necessary.</p>
        <nav className={styles.contents} aria-label="Article contents"><small>Contents</small><ol>{contents.map((item,index)=><li key={item}><a href={`#${slugify(item)}`}>{index+1}. {item}</a></li>)}</ol></nav>

        <section id={slugify(contents[0])}><h2>1. {contents[0]}</h2><h3>1. Householder planning permission</h3><p>A householder planning application is generally used when an extension falls outside permitted-development limitations or where those rights are unavailable. Examples may include two-storey side or larger two-storey rear extensions, work beyond the principal elevation, side extensions on designated land, extensions to flats or maisonettes, proposals exceeding the permitted dimensions, or work where rights have been removed. These are examples, not a complete legal test.</p><h3>2. Permitted development</h3><p>Permitted-development rights allow certain work to a house without an ordinary planning application, provided every relevant limitation and condition is satisfied. A small extension is not automatically permitted development. Assessment may cover the original house, previous additions, site coverage, depth, eaves and overall height, boundary distances, side-extension width, materials, upper-floor side windows, designated land, planning conditions, Article 4 directions and whether the property is a house rather than a flat.</p><h3>3. Larger home extension prior approval</h3><p>For qualifying houses outside designated land, a larger single-storey rear extension may use the neighbour-consultation process where it projects more than 4 metres and no more than 8 metres for a detached house, or more than 3 metres and no more than 6 metres for another house.</p><p>This applies only to qualifying single-storey rear extensions that meet the other permitted-development requirements. Birmingham City Council consults adjoining neighbours; where concerns are raised, it assesses the effect on their amenity. Work must not start until the process has concluded and the proposal is authorised. This is not an ordinary householder application.</p><h3>4. Lawful Development Certificate</h3><p>A Proposed Lawful Development Certificate provides a formal decision about whether proposed work would be lawful. It is not planning permission, but can provide valuable evidence when selling or remortgaging, appointing a contractor or demonstrating lawful status. Our <Link href="/services/planning-applications">planning application service</Link> can include advice on the appropriate route.</p></section>

        <section id={slugify(contents[1])}><h2>2. {contents[1]}</h2><aside className={styles.warning}><strong>Important:</strong><span>The following dimensions are only part of the permitted-development rules. Meeting one measurement does not establish that the whole proposal is lawful.</span></aside><h3>Single-storey rear extensions</h3><p>The standard rear projection limit is generally up to 4 metres for a detached house and up to 3 metres for another house, measured from the rear wall of the original house. Qualifying larger extensions may use the prior-approval route described above.</p><p>A single-storey extension must not normally exceed 4 metres overall height. Where any part is within 2 metres of a boundary, its eaves must not exceed 3 metres. Existing extensions can affect the measurement and allowance, while combined side-and-rear extensions must satisfy both sets of restrictions.</p><h3>Single-storey side extensions</h3><p>A qualifying side extension must generally be single storey, not exceed 4 metres in height and have a width no greater than half the width of the original house. Additional restrictions apply on designated land such as conservation areas.</p><h3>Two-storey rear extensions</h3><p>Some two-storey rear extensions may potentially qualify, but the rules are substantially more restrictive. Assessment can include projection, distance from the rear boundary, eaves and overall height, roof pitch, matching materials, side-facing upper-floor windows, previous extensions and designated-land restrictions. Obtain a property-specific assessment before relying on permitted development.</p><h3>Side-and-rear wraparound extensions</h3><p>A wraparound proposal must satisfy the relevant side and rear limitations together. Many larger arrangements therefore require planning permission.</p><h3>Front extensions</h3><p>Extensions forward of the principal elevation, or a side elevation fronting a highway, will commonly require planning permission, although the legal assessment remains property-specific.</p></section>

        <section id={slugify(contents[2])}><h2>3. {contents[2]}</h2><p>Permitted-development measurements generally refer to the house as it stood on 1 July 1948 or, where built later, as originally constructed. Previous extensions can therefore reduce or exhaust the remaining allowance.</p><p>For example, a rear addition may look original today but have been constructed later. A proposed further extension may need to be measured together with it. Old planning drawings, historic maps, sales particulars and council planning records can help establish the building’s history.</p></section>
        <section id={slugify(contents[3])}><h2>4. {contents[3]}</h2><p>Rights may be restricted or unavailable where the property is a flat or maisonette; the house was created through certain permitted-development changes of use; a planning condition removed the rights; an Article 4 direction applies; designated land introduces additional restrictions; the property is listed; the proposal fails any limitation or condition; or previous development has used the available allowance.</p><p>Listed-building consent can be required separately. The absence of a planning application does not remove heritage controls.</p></section>
        <section id={slugify(contents[4])}><h2>5. {contents[4]}</h2><p>Birmingham has numerous conservation areas in which development’s character and appearance receive additional consideration. Potentially sensitive locations include parts of <Link href="/locations/bournville-architects">Bournville</Link>, <Link href="/locations/edgbaston-architects">Edgbaston</Link>, <Link href="/locations/moseley-architects">Moseley</Link>, <Link href="/locations/harborne-architects">Harborne</Link>, <Link href="/locations/kings-heath-architects">Kings Heath</Link>, Jewellery Quarter residential edges and other designated neighbourhoods. This does not mean every property in those districts lies in a conservation area.</p><p>On designated land, side extensions do not receive the same Class A rights, multi-storey rear extensions face extra restrictions and external cladding and roof alterations may require permission. Trees in conservation areas can also be subject to a separate notification process.</p></section>
        <section id={slugify(contents[5])}><h2>6. {contents[5]}</h2><p>Birmingham City Council’s householder guidance explains that an extension’s design, size and location should be sympathetic to the existing house and respect its surroundings, including neighbours’ privacy and light.</p><h3>Relationship with the existing house</h3><p>Officers may consider scale, width, roof form, materials, architectural proportions and whether the original building remains visually legible.</p><h3>Neighbouring daylight and outlook</h3><p>Relevant factors include projection depth, nearby windows, boundaries, orientation, existing additions and ground levels. Angular tests can inform design, but the overall contextual effect matters.</p><h3>Privacy and overlooking</h3><p>Upper-floor side windows, raised terraces, balconies, proximity to gardens, floor-level changes and suitable obscure glazing can all be relevant.</p><h3>Street character</h3><p>Side-space retention, a possible terracing effect, gaps between buildings, front building lines, roof form, corner plots and public visibility may influence the design.</p><h3>Trees, drainage and site constraints</h3><p>Protected or conservation-area trees, drainage routes, sewers, flood risk and ground conditions can shape the proposal and supporting information. See <a href="https://www.birmingham.gov.uk/info/20160/planning_applications/3004/how_we_assess_planning_applications" target="_blank" rel="noopener noreferrer">Birmingham City Council’s current planning assessment guidance</a>.</p></section>
        <section id={slugify(contents[6])}><h2>7. {contents[6]}</h2><p>A 45-degree assessment can help indicate whether an extension may affect a neighbour’s daylight or outlook, but it is not an automatic pass-or-fail formula detached from context. Birmingham’s design guidance contains city notes concerning light, privacy and householder additions.</p><p>An assessment should identify which window is involved, whether it serves a habitable room, its position and orientation, the extension’s height and depth, the relationship between properties and existing obstructions or development.</p></section>

        <section id={slugify(contents[7])}><h2>8. {contents[7]}</h2><div className={styles.comparison}><article><h3>Planning permission</h3><p>Covers scale, appearance, land use, neighbour amenity, local character and planning policy.</p></article><article><h3>Building Regulations</h3><p>Covers structure, fire safety, thermal performance, ventilation, drainage, electrical safety, glazing and access.</p></article><article><h3>Party Wall etc. Act 1996</h3><p>May apply to boundary work, shared walls or excavation near neighbouring structures.</p></article></div><p>These systems are separate. Building Regulations approval may still be necessary where an extension is permitted development. Full-plans approval is usually the strongest route for a designed extension because coordinated technical information can be reviewed before construction.</p><p>Party-wall advice should be obtained from an appropriately qualified surveyor where required; this guide does not provide legal advice.</p></section>
        <section id={slugify(contents[8])}><h2>9. {contents[8]}</h2><p>A typical Birmingham householder application may include a location plan; existing and proposed site or block plans; existing and proposed floor plans and elevations; roof plans; sections where levels or relationships need explanation; design, access or heritage information where justified; and relevant tree, flood or drainage information.</p><p>Validation requirements depend on the proposal and current council requirements. Accurate drawings should show the complete existing property, not the extension in isolation.</p></section>
        <section id={slugify(contents[9])}><h2>10. {contents[9]}</h2><ol className={styles.process}><li><h3>Review the property and planning history</h3><p>Check property type, records, previous additions, conservation and listed status, Article 4 directions, conditions, protected trees and the likely route.</p></li><li><h3>Measure the existing house</h3><p>Record dimensions, openings, roof form, levels and relevant site relationships.</p></li><li><h3>Test design options</h3><p>Compare the brief with planning risk, layout, daylight, structure, drainage, cost and neighbouring impact.</p></li><li><h3>Confirm the application route</h3><p>Decide whether householder permission, larger-home-extension prior approval, an LDC or another consent is likely.</p></li><li><h3>Prepare and submit the application</h3><p>Coordinate the drawings, forms and supporting information.</p></li><li><h3>Respond during determination</h3><p>The council may request clarification or amendments, but is not obliged to negotiate every application into an acceptable form.</p></li><li><h3>Develop the Building Regulations package</h3><p>Once sufficiently settled, coordinate technical, structural and specialist design.</p></li></ol></section>
        <section id={slugify(contents[10])}><h2>11. {contents[10]}</h2><p>Ordinary householder applications are generally subject to the national statutory determination period for minor applications, commonly eight weeks, but actual times vary. A full programme must also allow for survey, design, client approval, document preparation, validation, requested changes, condition discharge where applicable, technical design, engineering and contractor pricing. Eight weeks is not a guaranteed overall service or council decision.</p></section>
        <section id={slugify(contents[11])}><h2>12. {contents[11]}</h2><p>Applications can encounter difficulty because of excessive depth or height, loss of light or outlook, overlooking, bulky roof form, a weak relationship with the house, excessive side-extension width, a terracing effect, incomplete drawings, missed conservation or tree constraints, overlooked previous extensions, misunderstanding a neighbour’s role, or starting before the appropriate approval. No one issue automatically determines an application; each proposal is assessed in context.</p></section>
        <section id={slugify(contents[12])}><h2>13. {contents[12]}</h2><p>Total pre-construction costs can include the architect’s survey, feasibility, design and planning drawings; the statutory application charge and any Planning Portal service charge; structural engineering; tree, drainage or heritage advice; LDC or prior-approval charges; technical drawings; Building Control charges; and party-wall advice. Statutory charges change, so this guide does not hard-code them.</p><aside className={styles.feeCta}><div><small>Early cost guidance</small><h3>Get an indicative architectural fee</h3><p>The calculator provides an early indication only. A written, project-specific proposal is required.</p></div><Link className="btn primary" href="/estimate">Use the fee calculator <ArrowRight size={16}/></Link></aside></section>
        <section id={slugify(contents[13])}><h2>14. {contents[13]}</h2><p>An architect is not legally required for most householder applications. However, an architect can interpret the brief, identify constraints, test layouts, improve the relationship between old and new, prepare coordinated drawings, advise on the likely route, respond to planning considerations and develop the project for <Link href="/services/building-regulations">Building Regulations</Link>.</p><p>Architectural designers and technicians may also offer appropriate services. Anyone using the title architect in professional practice must be registered with ARB. Our separate guide explains <Link href="/journal/how-to-choose-the-best-architect-in-birmingham">how to compare Birmingham architects</Link>.</p></section>
        <section id={slugify(contents[14])}><h2>15. {contents[14]}</h2><p>Hepburn Architects provides director-led residential architectural services across Birmingham and the wider West Midlands.</p><p>Depending on the commission, our <Link href="/services/house-extensions">house-extension service</Link> can include:</p><ul><li>initial property and planning review;</li><li>measured survey and feasibility design;</li><li>existing and proposed drawings;</li><li>permitted-development assessment;</li><li>householder planning application;</li><li>Proposed Lawful Development Certificate;</li><li>larger-home-extension prior approval;</li><li>Building Regulations drawings;</li><li>coordination with structural engineers and other consultants.</li></ul><p>We do not guarantee planning permission. Our role is to understand the property, identify the relevant constraints and prepare the strongest reasonable design and submission for the client’s brief.</p><div className="actions"><Link className="btn primary" href="/contact">Discuss your Birmingham extension</Link><Link className="btn secondary" href="/services/house-extensions">View our house-extension service</Link><Link className="btn secondary" href="/locations/birmingham-architects">View Birmingham architects</Link></div></section>

        <section id="birmingham-project-example"><h2>Birmingham extension project example</h2><div className={styles.project}><Image src="/images/birmingham-residential-project.jpg" alt="Family home extension in Sutton Coldfield, Birmingham" width={1024} height={485} sizes="(max-width: 760px) 100vw, 400px"/><div><small>Sutton Coldfield · Single and two-storey extension</small><h3>Family Home Extension</h3><p>A coordinated rear, side and front extension strategy designed to create a larger kitchen and dining space, additional bedrooms and improved family accommodation.</p><Link href="/projects/sutton-coldfield-extension">View the complete project <ArrowRight size={15}/></Link></div></div><p>Explore further <Link href="/projects">residential projects</Link> from the practice.</p></section>
        <section id="birmingham-extension-planning-checklist" className={styles.printChecklist}><h2>Birmingham extension planning checklist</h2><ul>{["Is the property a house rather than a flat?","What is the original house?","Have previous extensions been identified?","Are permitted-development rights intact?","Is the property listed or within a conservation area?","Are any trees protected?","Does the proposal extend beyond a side wall?","What is the rear projection?","What are the eaves and overall heights?","How close is the extension to the boundary?","Could neighbouring windows lose light or outlook?","Will new windows overlook neighbouring property?","Is larger-home-extension prior approval relevant?","Would an LDC provide useful formal confirmation?","Is Building Regulations approval required?","Could the Party Wall Act apply?","Have drainage and structural requirements been reviewed?","Are the drawings sufficient for the intended application?"].map(item=><li key={item}>{item}</li>)}</ul></section>
        <section id="useful-independent-resources" className={styles.resources}><h2>Useful independent resources</h2><ul><li><a href="https://www.birmingham.gov.uk/info/20008/planning_and_development/98/do_i_need_planning_permission" target="_blank" rel="noopener noreferrer">Birmingham City Council: check whether permission is required <ExternalLink size={15}/></a></li><li><a href="https://www.birmingham.gov.uk/info/20160/planning_applications/3004/how_we_assess_planning_applications" target="_blank" rel="noopener noreferrer">Birmingham City Council: how applications are assessed <ExternalLink size={15}/></a></li><li><a href="https://www.gov.uk/government/publications/permitted-development-rights-for-householders-technical-guidance/permitted-development-rights-for-householders-technical-guidance" target="_blank" rel="noopener noreferrer">GOV.UK householder permitted-development technical guidance <ExternalLink size={15}/></a></li><li><a href="https://www.gov.uk/building-regulations-approval/how-to-apply" target="_blank" rel="noopener noreferrer">GOV.UK Building Regulations approval guidance <ExternalLink size={15}/></a></li><li><a href="https://arb.org.uk/architects-register/" target="_blank" rel="noopener noreferrer">Official ARB Architects Register <ExternalLink size={15}/></a></li></ul><p>More practical material is available in our <Link href="/knowledge-centre">Knowledge Centre</Link>.</p></section>
        <section id="frequently-asked-questions" className={styles.faq}><h2>Frequently asked questions</h2>{faqs.map(faq=><details key={faq.question}><summary>{faq.question}</summary><p>{faq.answer}</p></details>)}</section>
        <aside className="content-cta"><small className="eyebrow">Planning a Birmingham extension?</small><h2>Review the property before choosing an approval route.</h2><p>Speak directly with Hepburn Architects about the brief, planning history and likely next steps.</p><Link className="btn primary" href="/contact">Book an initial consultation <ArrowRight size={17}/></Link></aside>
      </div>
    </div></article>
  </>;
}
