import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { ArrowRight, ExternalLink, Newspaper } from "lucide-react";
import { StructuredData } from "@/components/StructuredData";
import { buildGraph } from "@/lib/structured-data";
import { site } from "@/lib/site";
import styles from "../house-extension-planning-permission-birmingham-2026-guide/page.module.css";

const title = "Loft Conversion Planning Rules in Birmingham: 2026 Guide";
const description = "Do you need planning permission for a loft conversion in Birmingham? Understand dormer, hip-to-gable and rooflight permitted-development rules in this practical 2026 guide.";
const schemaDescription = "A practical guide to planning permission, permitted development, dormers, hip-to-gable extensions and Lawful Development Certificates for Birmingham loft conversions.";
const path = "/journal/loft-conversion-planning-rules-birmingham";
const url = `${site.url}${path}`;
const image = `${site.url}/images/birmingham-residential-project.jpg`;
const publicationDate = "2026-08-02";

const faqs = [
  { question: "Do I need planning permission for a loft conversion in Birmingham?", answer: "Not always. Internal loft-conversion work may not require planning permission, and some dormers, hip-to-gable extensions and rooflights can qualify as permitted development. The property and complete proposal must satisfy all relevant limitations and conditions." },
  { question: "How large can a loft conversion be under permitted development?", answer: "Class B normally permits up to 40 cubic metres of additional roof space for a terraced house and up to 50 cubic metres for a semi-detached or detached house. Previous roof enlargements count towards the allowance, and compliance with the volume limit alone does not make the proposal permitted development." },
  { question: "Does a rear dormer need planning permission in Birmingham?", answer: "Some rear dormers may qualify as permitted development where all Class B requirements are satisfied. Planning permission may be required where the property is in a conservation area, permitted-development rights have been removed or the proposed dormer fails another limitation or condition." },
  { question: "Does a front dormer need planning permission?", answer: "A dormer extending beyond a roof slope that forms the principal elevation and fronts a highway is not permitted development under Class B. For many conventional houses, this means a front dormer requires planning permission, although the specific elevation must be assessed." },
  { question: "Is a hip-to-gable loft conversion permitted development?", answer: "Some hip-to-gable conversions can qualify under Class B. The assessment must consider roof volume, property status, conservation designation, ridge height, previous alterations and whether permitted-development rights remain available." },
  { question: "Can I convert a loft in a conservation area without planning permission?", answer: "Internal work may not require planning permission, but roof enlargements under Class B are not permitted development on article 2(3) land, which includes conservation areas. Dormers and hip-to-gable enlargements will therefore normally require planning permission in a conservation area." },
  { question: "Do permitted-development rights apply to flats?", answer: "Part 1 householder permitted-development rights generally apply to dwellinghouses rather than flats or maisonettes. External loft alterations associated with a flat will normally require a planning assessment and may require planning permission." },
  { question: "Can a loft conversion include a balcony?", answer: "Balconies, verandahs and raised platforms are not permitted under Class B. A roof terrace or projecting balcony will normally require planning permission and may raise privacy and neighbour-amenity concerns." },
  { question: "Do I need a Lawful Development Certificate?", answer: "An LDC is not always mandatory, but it can provide formal confirmation that a proposed permitted-development loft conversion is lawful. This can be useful for contractors, lenders and future conveyancing." },
  { question: "Do I need Building Regulations approval?", answer: "A loft conversion will normally require Building Regulations approval even where planning permission is not needed. Building Regulations cover matters including structure, stairs, fire safety, insulation and ventilation." },
  { question: "Can Hepburn Architects guarantee approval?", answer: "No. Decisions on planning permission and Lawful Development Certificates are made by the local planning authority. Hepburn Architects can assess the property, develop the design and prepare a coordinated submission, but approval cannot legitimately be guaranteed." },
] as const;

const contents = ["The main approval routes", "How much additional roof space is allowed?", "Rear dormer loft conversions", "Front dormers and roof alterations facing a highway", "Hip-to-gable loft conversions", "Rooflights and skylights", "Conservation areas and historic neighbourhoods", "Flats, maisonettes and converted buildings", "When permitted-development rights may be unavailable", "Side-facing loft windows", "Balconies and roof terraces", "What Birmingham City Council considers", "Planning permission and Building Regulations", "Fire safety in a loft conversion", "Is there enough headroom?", "What drawings are normally required?", "The Birmingham loft-conversion process", "How long does an application take?", "Common planning mistakes", "Should I apply for an LDC?", "How much does a design service cost?", "How Hepburn Architects supports loft conversions"] as const;
const slugify = (value: string) => value.toLowerCase().replace(/[‘’?]/g, "").replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");

export const metadata: Metadata = {
  title: { absolute: "Loft Conversion Planning Rules Birmingham | 2026 Guide" }, description, alternates: { canonical: url },
  openGraph: { title: "Loft Conversion Planning Rules in Birmingham: 2026 Guide", description: schemaDescription, url, type: "article", publishedTime: publicationDate, modifiedTime: publicationDate, authors: [`${site.url}/about`], images: [{ url: image, width: 1024, height: 485, alt: "Residential extension project in Sutton Coldfield, Birmingham" }] },
  twitter: { card: "summary_large_image", title: "Loft Conversion Planning Rules in Birmingham: 2026 Guide", description: schemaDescription, images: [image] },
};

export default function BirminghamLoftPlanningGuidePage() {
  const schema = { "@context": "https://schema.org", "@graph": [
    { "@type": "BlogPosting", "@id": `${url}#article`, headline: title, description: schemaDescription, author: { "@id": `${site.url}/#david-hepburn` }, publisher: { "@id": `${site.url}/#organization` }, mainEntityOfPage: url, datePublished: publicationDate, dateModified: publicationDate, image: { "@type": "ImageObject", url: image, width: 1024, height: 485 }, articleSection: "Planning guidance", inLanguage: "en-GB" },
    { "@type": "WebPage", "@id": `${url}#webpage`, url, name: title, description: schemaDescription, isPartOf: { "@id": `${site.url}/#website` }, primaryImageOfPage: { "@id": `${url}#primaryimage` }, breadcrumb: { "@id": `${url}#breadcrumb` }, mainEntity: { "@id": `${url}#article` }, inLanguage: "en-GB" },
    { "@type": "ImageObject", "@id": `${url}#primaryimage`, url: image, width: 1024, height: 485 },
    { "@type": "BreadcrumbList", "@id": `${url}#breadcrumb`, itemListElement: [{ "@type": "ListItem", position: 1, name: "Home", item: `${site.url}/` }, { "@type": "ListItem", position: 2, name: "Journal", item: `${site.url}/blog` }, { "@type": "ListItem", position: 3, name: title, item: url }] },
    { "@type": "FAQPage", "@id": `${url}#faq`, mainEntity: faqs.map((faq) => ({ "@type": "Question", name: faq.question, acceptedAnswer: { "@type": "Answer", text: faq.answer } })) },
  ] };
  return <><StructuredData data={buildGraph(schema)} /><article className={`section ${styles.article}`}><div className="shell article-page">
    <nav aria-label="Breadcrumb" className="muted small-copy"><Link href="/">Home</Link> · <Link href="/blog">Journal</Link></nav><small className="eyebrow"><Newspaper size={14}/> Planning guidance</small><h1>{title}</h1>
    <p className="lead">Many Birmingham loft conversions can potentially proceed under permitted development, but dormers, hip-to-gable extensions, rooflights and conservation-area properties are subject to detailed restrictions. This guide explains the main approval routes and the checks to make before starting work.</p><p className={styles.byline}>Published 2 August 2026 · 10 minutes read · By <Link href="/about">David Hepburn</Link></p>
    <figure className={styles.hero}><Image src="/images/birmingham-residential-project.jpg" alt="Residential extension project in Sutton Coldfield, Birmingham" width={1024} height={485} priority sizes="(max-width: 1100px) 100vw, 1100px"/><figcaption>Genuine Hepburn Architects residential project in Sutton Coldfield, Birmingham. This image is not presented as a loft-conversion case study.</figcaption></figure>
    <div className={styles.body}><p>A loft conversion can add a bedroom, home office, bathroom or flexible living space without increasing the footprint of a Birmingham home.</p><aside className={styles.question}><strong>Do I need planning permission for a loft conversion?</strong></aside><p>In many cases, internal conversion of an existing roof space does not itself require planning permission. External work such as dormers, hip-to-gable extensions, rooflights, balconies and changes to the roof profile may instead require a permitted-development assessment, Proposed Lawful Development Certificate, householder planning permission, listed-building consent or another approval.</p><p>The correct route depends on the property, roof design, location, previous alterations and exact proposal. Building Regulations approval is normally required even where planning permission is not.</p>
    <nav className={styles.contents} aria-label="Article contents"><small>Contents</small><ol>{contents.map((item,index)=><li key={item}><a href={`#${slugify(item)}`}>{index+1}. {item}</a></li>)}</ol></nav>

    <section id={slugify(contents[0])}><h2>1. {contents[0]}</h2><h3>1. Internal conversion without material external alteration</h3><p>Converting existing roof space internally may not require planning permission where there is no material external change. Work can include a new floor structure, insulation, partitions, stairs, fire protection, internal doors and a bathroom. Rooflights, dormers, vents, flues and roof alterations must be assessed separately, while Building Regulations will normally apply.</p><h3>2. Permitted development under Class B</h3><p>Class B covers additions or alterations that enlarge a dwellinghouse’s roof, including many dormer and hip-to-gable arrangements. Every applicable limitation and condition must be met; volume alone does not establish permitted development.</p><h3>3. Roof alterations under Class C</h3><p>Class C generally covers other roof alterations that do not enlarge the dwellinghouse, including qualifying rooflights. Rooflights and dormers are therefore assessed differently.</p><h3>4. Householder planning permission</h3><p>Permission may be required where a roof enlargement exceeds Class B limits, projects from the principal-elevation roof slope fronting a highway, lies on designated land, includes a balcony or platform, rises above the existing roof, has lost permitted-development rights, concerns a flat or maisonette, or fails a design condition. This is illustrative, not a complete legal test.</p><h3>5. Proposed Lawful Development Certificate</h3><p>An LDC gives a formal council decision on whether proposed work would be lawful. It is not planning permission, but can provide evidence for conveyancing, remortgaging, future sales, contractors and Building Control. Our <Link href="/services/planning-applications">planning service</Link> can advise on the appropriate submission.</p></section>
    <section id={slugify(contents[1])}><h2>2. {contents[1]}</h2><aside className={styles.warning}><strong>Important:</strong><span>The roof-volume allowance is only one part of the assessment. Every relevant limitation and condition must be satisfied.</span></aside><p>Class B normally limits total additional roof space to 40 cubic metres for a terraced house and 50 cubic metres for a semi-detached or detached house. The calculation relates to the original roof space, includes earlier owners’ roof enlargements, and must consider all proposed dormers and enlargements together.</p><p>Volume should be calculated accurately from external dimensions. The allowance is not automatically available where other restrictions apply, and the legal definition of a terrace must be checked rather than inferred from an everyday description.</p></section>
    <section id={slugify(contents[2])}><h2>3. {contents[2]}</h2><p>A rear dormer can sometimes qualify under Class B. Relevant checks include total added volume, ridge height, position, whether the slope forms the principal elevation and fronts a highway, distance from the eaves, materials, side windows, conservation status, earlier enlargements and removed rights.</p><p>The enlargement must not exceed the existing roof’s highest part. So far as practicable, its edge closest to the original eaves must be at least 20 centimetres away, measured along the roof slope; that setback does not apply to a hip-to-gable enlargement. It must not overhang the outer face of the original wall, subject to the detailed Class B wording. A full-width rear dormer is not automatically lawful.</p></section>
    <section id={slugify(contents[3])}><h2>4. {contents[3]}</h2><p>Class B does not permit an enlargement beyond an existing roof slope that both forms the principal elevation and fronts a highway. For many conventional Birmingham houses this means a front dormer needs planning permission.</p><p>Principal elevation and highway relationships can require specific assessment on corner plots, unusual access arrangements or buildings with several prominent elevations. A flush or low-profile front rooflight may potentially qualify under Class C if all conditions are met.</p></section>
    <section id={slugify(contents[4])}><h2>5. {contents[4]}</h2><p>A hip-to-gable conversion raises a hipped roof’s sloping side vertically to form a new gable wall and additional internal space. Some qualify under Class B, subject to volume, designated-land status, intact rights, ridge height, materials, earlier additions, combined dormer volume and the building being a house.</p><p>The normal 20-centimetre eaves setback does not apply to the hip-to-gable element itself. Permission may still be required where any other Class B requirement or local restriction is not satisfied.</p></section>
    <section id={slugify(contents[5])}><h2>6. {contents[5]}</h2><p>Rooflights are commonly assessed under Class C because they do not normally enlarge the dwellinghouse. A qualifying installation must generally project no more than 0.15 metres beyond the original roof plane, remain below the original roof’s highest part and meet privacy conditions on a side-facing slope.</p><p>A side-facing roof window must generally be obscure glazed and non-opening unless its opening section is more than 1.7 metres above the internal floor. Projecting roof windows, roof balconies and altered roof forms may require a different assessment.</p></section>
    <section id={slugify(contents[6])}><h2>7. {contents[6]}</h2><p>Class B roof enlargements are not permitted development on article 2(3) land, which includes conservation areas. A dormer or hip-to-gable extension there will therefore normally require planning permission.</p><p>Birmingham has designated parts of <Link href="/locations/bournville-architects">Bournville</Link>, <Link href="/locations/edgbaston-architects">Edgbaston</Link>, <Link href="/locations/harborne-architects">Harborne</Link>, <Link href="/locations/moseley-architects">Moseley</Link>, <Link href="/locations/kings-heath-architects">Kings Heath</Link>, Sutton Coldfield, the Jewellery Quarter and other historic areas. This does not mean each entire district is designated.</p><p>Public visibility, roof form, dormer scale and position, materials, chimneys, terrace uniformity and conservation character can matter. Rooflights still need Class C and any Article 4 direction assessed.</p></section>
    <section id={slugify(contents[7])}><h2>8. {contents[7]}</h2><p>Part 1 householder rights generally apply to dwellinghouses, not flats or maisonettes. External loft alterations serving a flat may therefore need planning permission.</p><p>Ownership of roof space does not establish planning permission or a legal right to build. Leasehold and freeholder consent, title rights, party-wall matters, Building Regulations, fire safety and access may also require advice. This article is not legal advice.</p></section>
    <section id={slugify(contents[8])}><h2>9. {contents[8]}</h2><p>Rights may be unavailable because a planning condition or Article 4 direction restricts them; the site is in a conservation area; the house arose through specified change-of-use rights; the property is a flat; previous work used the volume; a condition fails; or the building is listed.</p><p>Listed-building consent is independent. Check planning history, original conditions, conservation maps, Article 4 directions, listing status and previous LDCs before design is fixed.</p></section>
    <section id={slugify(contents[9])}><h2>10. Do side-facing loft windows need obscure glazing?</h2><p>Class B conditions generally require windows in a side wall or side roof slope of the enlargement to be obscure glazed and non-opening unless the opening part is at least 1.7 metres above the room floor. This protects privacy.</p><p>Building Regulations requirements for escape, ventilation and safety glazing remain separate. Obscure glazing does not automatically resolve every overlooking concern in a planning application.</p></section>
    <section id={slugify(contents[10])}><h2>11. Can a loft conversion include a balcony or roof terrace?</h2><p>Class B does not permit balconies, verandahs or raised platforms, so a roof terrace or projecting balcony will normally require planning permission. A Juliet balcony without an external platform may be treated differently, but its door or window alteration and appearance still need assessment.</p><p>Overlooking, noise, neighbour amenity, visual prominence, safety and compatibility may all be considered.</p></section>
    <section id={slugify(contents[11])}><h2>12. {contents[11]}</h2><p>Where permission is required, Birmingham City Council assesses the individual context.</p><h3>Roof form and scale</h3><p>Whether the work remains subordinate to and compatible with the original building.</p><h3>Street and terrace character</h3><p>Whether an established roof pattern is disrupted or the work becomes overly prominent.</p><h3>Dormer design</h3><p>Width, height, roof form, cheeks, cladding, window relationships, roof-edge spacing and neighbouring dormers may matter.</p><h3>Privacy, heritage and amenity</h3><p>Side and rear windows, terraces, balconies, ground levels, listing or conservation status, outlook, privacy and visual dominance can be relevant. No design convention guarantees approval.</p></section>
    <section id={slugify(contents[12])}><h2>13. {contents[12]} are separate</h2><div className={styles.comparison}><article><h3>Planning permission</h3><p>External appearance, roof form, scale, local character, conservation, neighbour amenity and policy.</p></article><article><h3>Building Regulations</h3><p>Floor and roof structure, stairs, fire safety, insulation, ventilation, windows, guarding, electrics and drainage.</p></article><article><h3>Other consents</h3><p>Listed-building, freeholder, leasehold and party-wall requirements where applicable.</p></article></div><p>A loft conversion will normally need Building Regulations approval even where external work is permitted development. See our <Link href="/services/building-regulations">technical design service</Link>.</p></section>
    <section id={slugify(contents[13])}><h2>14. {contents[13]}</h2><p>Fire strategy depends on storey count, stairs, room positions, escape arrangements, doors on the escape route, alarms, separation, open-plan layouts and existing construction. Converting a typical two-storey house to include loft accommodation creates a three-storey dwelling, which can materially change the strategy.</p><p>There is no universal door or layout solution. Architectural design and Building Control assessment should be coordinated.</p></section>
    <section id={slugify(contents[14])}><h2>15. {contents[14]}</h2><p>Planning compliance and physical feasibility are different. Ridge height, roof structure, ceilings, stair position, insulation and floor build-ups, tanks, services, chimneys and structural support can constrain a loft.</p><p>Building Regulations guidance commonly uses 2 metres as desired clear stair headroom, with limited loft-conversion concessions where space is constrained. This is not a universal minimum room height or planning requirement. An early measured survey and feasibility study can prevent an impractical design progressing.</p></section>
    <section id={slugify(contents[15])}><h2>16. {contents[15]}</h2><p>A planning or LDC submission may include a location plan; block plan where required; existing and proposed plans, elevations and roof plans; roof and stair sections; volume calculations; material notes; and photographs. Technical information may add floor and roof structure, stair design, insulation, ventilation, fire safety, drainage, electrical and detection details, plus engineering calculations. Exact requirements depend on the project and route.</p></section>
    <section id={slugify(contents[16])}><h2>17. {contents[16]}</h2><ol className={styles.process}><li><h3>Review the property</h3><p>Check house or flat status, history, rights, conservation, Article 4 and listing.</p></li><li><h3>Survey the existing roof</h3><p>Record ridge, pitch, structure, ceilings, chimneys, adjoining form and stair options.</p></li><li><h3>Test feasibility</h3><p>Assess headroom, stairs, layout, fire, structure, appearance and planning route.</p></li><li><h3>Confirm the approval route</h3><p>Identify internal-only work, permitted development, LDC, planning or listed-building consent.</p></li><li><h3>Prepare the submission</h3><p>Produce coordinated drawings and supporting information.</p></li><li><h3>Develop the technical design</h3><p>Coordinate Building Regulations, engineering, fire, insulation, ventilation, drainage and details.</p></li></ol></section>
    <section id={slugify(contents[17])}><h2>18. {contents[17]}</h2><p>Householder planning applications are commonly subject to the national statutory eight-week period for minor applications, and Proposed LDC applications also have a statutory determination period. Validation, amendments and workload can affect actual timing. Survey, design, technical development and contractor pricing sit outside that period, and no decision date can be guaranteed.</p></section>
    <section id={slugify(contents[18])}><h2>19. {contents[18]}</h2><p>Common mistakes include treating volume as the only rule; missing earlier additions; misidentifying the original roof; treating a flat as a house; putting a front dormer under Class B; overlooking conservation status; exceeding the ridge; adding a terrace; omitting qualifying obscure glazing; submitting incomplete roof drawings; starting without confirmation; ignoring fire and technical approval; and planning the room before resolving the stair. These do not automatically lead to enforcement or refusal, but each can undermine the route or design.</p></section>
    <section id={slugify(contents[19])}><h2>20. {contents[19]}</h2><p>An LDC is often worth considering even where a designer believes the work is permitted. It supplies a formal council decision, clearer evidence for sale, contractors, lenders and solicitors, and confirmation tied to the assessed drawings. The completed work must match those drawings. An LDC does not replace Building Regulations or other consents.</p></section>
    <section id={slugify(contents[20])}><h2>21. {contents[20]}</h2><p>Professional and approval costs may include survey, feasibility, planning or LDC drawings, the current application charge, engineering, Building Regulations drawings, Building Control, party-wall advice, specialist fire input and services alterations. Statutory charges change and are not hard-coded here.</p><aside className={styles.feeCta}><div><small>Early cost guidance</small><h3>Get an indicative architectural fee</h3><p>The calculator provides an early indication only. A written, project-specific proposal is required.</p></div><Link className="btn primary" href="/estimate">Use the fee calculator <ArrowRight size={16}/></Link></aside></section>
    <section id={slugify(contents[21])}><h2>22. {contents[21]}</h2><p>Hepburn Architects provides director-led residential architectural services across Birmingham and the wider West Midlands.</p><p>Depending on the property and appointment, our <Link href="/services/loft-conversions">loft-conversion service</Link> can include planning-history review, measured survey, feasibility, stair and layout design, permitted-development assessment, volume calculations, an LDC or householder application, Building Regulations drawings and specialist coordination.</p><p>We do not guarantee planning permission or lawful-development approval. Our role is to assess the property, explain constraints and prepare a clear, coordinated proposal.</p><div className="actions"><Link className="btn primary" href="/contact">Discuss your Birmingham loft conversion</Link><Link className="btn secondary" href="/services/loft-conversions">View our loft-conversion service</Link><Link className="btn secondary" href="/locations/birmingham-architects">View Birmingham architects</Link></div></section>

    <section id="birmingham-project-example"><h2>Genuine Birmingham residential project</h2><div className={styles.project}><Image src="/images/birmingham-residential-project.jpg" alt="Family home extension in Sutton Coldfield, Birmingham" width={1024} height={485} sizes="(max-width: 760px) 100vw, 400px"/><div><small>Sutton Coldfield · Residential extension</small><h3>Family Home Extension</h3><p>A coordinated rear, side and front extension strategy for a Birmingham family home. It is included as genuine local residential evidence and is not described as a loft conversion.</p><Link href="/projects/sutton-coldfield-extension">View the complete project <ArrowRight size={15}/></Link></div></div><p>Explore further <Link href="/projects">published projects</Link>.</p></section>
    <section id="birmingham-loft-conversion-planning-checklist" className={styles.printChecklist}><h2>Birmingham loft-conversion planning checklist</h2><ul>{["Is the property a house, flat or maisonette?","Are permitted-development rights intact?","Is the property within a conservation area?","Is the building listed?","Has an Article 4 direction been checked?","Have previous roof enlargements been identified?","What is the original roof form?","Is the house terraced, semi-detached or detached?","What additional roof volume is proposed?","Does any work exceed the existing ridge height?","Does a roof enlargement face a highway?","Is that roof slope part of the principal elevation?","Is a hip-to-gable enlargement proposed?","Is a dormer set appropriately above the eaves?","Are side windows obscure glazed where required?","Is a balcony or roof terrace proposed?","Would an LDC provide useful confirmation?","Is there sufficient headroom?","Can a compliant staircase be accommodated?","Has the fire strategy been reviewed?","Is structural engineering required?","Is Building Regulations approval required?","Could the Party Wall Act apply?"].map(item=><li key={item}>{item}</li>)}</ul></section>
    <section id="useful-independent-resources" className={styles.resources}><h2>Useful independent resources</h2><ul><li><a href="https://www.gov.uk/government/publications/permitted-development-rights-for-householders-technical-guidance/permitted-development-rights-for-householders-technical-guidance" target="_blank" rel="noopener noreferrer">GOV.UK householder permitted-development technical guidance <ExternalLink size={15}/></a></li><li><a href="https://www.planningportal.co.uk/permission/common-projects/loft-conversion/planning-permission" target="_blank" rel="noopener noreferrer">Planning Portal loft-conversion planning guidance <ExternalLink size={15}/></a></li><li><a href="https://www.birmingham.gov.uk/info/20008/planning_and_development/98/do_i_need_planning_permission" target="_blank" rel="noopener noreferrer">Birmingham City Council planning-permission checking service <ExternalLink size={15}/></a></li><li><a href="https://www.gov.uk/building-regulations-approval/how-to-apply" target="_blank" rel="noopener noreferrer">GOV.UK Building Regulations approval guidance <ExternalLink size={15}/></a></li><li><a href="https://arb.org.uk/architects-register/" target="_blank" rel="noopener noreferrer">Official ARB Architects Register <ExternalLink size={15}/></a></li></ul><p>See also our <Link href="/knowledge-centre">Knowledge Centre</Link>, <Link href="/journal/house-extension-planning-permission-birmingham-2026-guide">Birmingham extension planning guide</Link> and guide to <Link href="/journal/how-to-choose-the-best-architect-in-birmingham">selecting an architect</Link>.</p></section>
    <section id="frequently-asked-questions" className={styles.faq}><h2>Frequently asked questions</h2>{faqs.map(faq=><details key={faq.question}><summary>{faq.question}</summary><p>{faq.answer}</p></details>)}</section>
    <aside className="content-cta"><small className="eyebrow">Considering a Birmingham loft conversion?</small><h2>Review the roof, stair and approval route together.</h2><p>Speak directly with Hepburn Architects about feasibility, planning and technical design.</p><Link className="btn primary" href="/contact">Book an initial consultation <ArrowRight size={17}/></Link></aside>
    </div></div></article></>;
}
