export type PageItem = {
  slug: string;
  title: string;
  shortTitle: string;
  description: string;
  intro: string;
  points: string[];
};

export type LocationItem = PageItem & {
  seoTitle: string;
  localContext: string;
  nearbyAreas: string[];
  serviceSlugs: string[];
};

export const services: PageItem[] = [
  { slug:"house-extensions", title:"House Extension Architect", shortTitle:"House extensions", description:"Architectural design, planning and Building Regulations for single, two-storey and wrap-around house extensions.", intro:"Thoughtful extensions that improve space, daylight and long-term value while respecting the character of the existing home.", points:["Feasibility and planning strategy","Design and planning drawings","Building Regulations packages","Coordination with structural engineers"] },
  { slug:"loft-conversions", title:"Loft Conversion Architect", shortTitle:"Loft conversions", description:"Design and technical support for dormer, hip-to-gable, mansard and rooflight loft conversions.", intro:"Turn underused roof space into practical bedrooms, offices and family accommodation through a compliant, well-resolved design.", points:["Permitted development checks","Dormer and stair design","Fire-safety coordination","Building Regulations drawings"] },
  { slug:"new-build-homes", title:"New Build Home Architect", shortTitle:"New-build homes", description:"Site appraisal, planning design and technical packages for individual homes and small residential developments.", intro:"Site-responsive new homes designed around planning policy, context, access, amenity and buildability.", points:["Site feasibility","Planning strategy","Design and Access Statements","Technical drawing packages"] },
  { slug:"hmo-conversions", title:"HMO Conversion Architect", shortTitle:"HMO conversions", description:"Planning, space standards, fire-safety layouts and Building Regulations support for HMO conversions.", intro:"Practical HMO layouts balancing occupancy, amenity, fire safety, licensing and local planning policy.", points:["Article 4 and use-class checks","Space-standard reviews","Fire strategy coordination","Planning and technical drawings"] },
  { slug:"planning-applications", title:"Planning Application Architect", shortTitle:"Planning applications", description:"Planning drawings, statements and submission support for residential projects and changes of use.", intro:"Clear planning strategies built around the development plan, site constraints and likely officer concerns.", points:["Planning policy review","Pre-application advice","Planning statements","Negotiation and amendments"] },
  { slug:"building-regulations", title:"Building Regulations Drawings", shortTitle:"Building Regulations", description:"Detailed residential technical drawings coordinated with Parts A to S of the Building Regulations.", intro:"Clear technical information designed to support Building Control approval and a smoother construction process.", points:["Construction details","Fire and thermal compliance","Drainage and ventilation","Consultant coordination"] }
];

export const locations: LocationItem[] = [
  {"slug": "birmingham", "title": "Residential Architect Birmingham", "shortTitle": "Birmingham", "seoTitle": "Residential Architect Birmingham | Extensions, Planning & Building Regulations", "description": "Residential architect in Birmingham for house extensions, loft conversions, new homes, HMOs, planning applications and Building Regulations drawings.", "intro": "Hepburn Architects provides director-led residential architecture for homeowners, developers and property investors across Birmingham and the wider West Midlands.", "localContext": "Birmingham contains a wide range of Victorian, Edwardian, inter-war and contemporary housing. Successful residential projects need to respond to the character of the street, neighbouring amenity, parking, trees and the relevant Birmingham planning policies rather than relying on a standard design.", "nearbyAreas": ["Harborne", "Edgbaston", "Moseley", "Sutton Coldfield", "Solihull", "Handsworth Wood"], "serviceSlugs": ["house-extensions", "loft-conversions", "planning-applications", "building-regulations"], "points": ["House extensions and remodelling", "Loft conversions and roof alterations", "HMOs, flats and changes of use", "Planning and Building Regulations"]},
  {"slug": "solihull", "title": "Residential Architect Solihull", "shortTitle": "Solihull", "seoTitle": "Residential Architect Solihull | House Extensions & New Homes", "description": "Residential architect in Solihull for extensions, remodelling, new homes, planning applications and Building Regulations drawings.", "intro": "Design-led residential architecture for homes and development sites across Solihull, including extensions, remodelling, replacement dwellings and new-build homes.", "localContext": "Projects in Solihull often require careful consideration of established suburban character, mature landscaping, neighbour amenity and, in some areas, Green Belt or conservation constraints. We develop the design and planning case together from the outset.", "nearbyAreas": ["Knowle", "Dorridge", "Shirley", "Olton", "Balsall Common", "Birmingham"], "serviceSlugs": ["house-extensions", "new-build-homes", "planning-applications", "building-regulations"], "points": ["House extensions and remodelling", "Replacement and new-build homes", "Planning strategy and applications", "Technical design"]},
  {"slug": "moseley", "title": "Residential Architect Moseley", "shortTitle": "Moseley", "seoTitle": "Residential Architect Moseley | Extensions & Loft Conversions", "description": "Residential architect in Moseley for period-home extensions, loft conversions, planning applications and Building Regulations drawings.", "intro": "Context-sensitive architecture for period homes, family properties and conservation-area sites across Moseley and south Birmingham.", "localContext": "Moseley has a strong architectural identity with many Victorian and Edwardian homes, mature plots and conservation-area streets. Alterations need to improve modern family living while respecting original proportions, materials and the wider street scene.", "nearbyAreas": ["Kings Heath", "Balsall Heath", "Edgbaston", "Harborne", "Hall Green", "Birmingham"], "serviceSlugs": ["house-extensions", "loft-conversions", "planning-applications", "building-regulations"], "points": ["Period-home extensions", "Loft conversions", "Conservation-sensitive design", "Building Regulations"]},
  {"slug": "harborne", "title": "Residential Architect Harborne", "shortTitle": "Harborne", "seoTitle": "Residential Architect Harborne | House Extensions & Remodelling", "description": "Residential architect in Harborne for kitchen extensions, whole-house remodelling, loft conversions and planning applications.", "intro": "High-quality residential design for Harborne homes, from rear extensions and internal remodelling to larger two-storey additions and loft conversions.", "localContext": "Harborne includes terraces, period villas, inter-war houses and modern infill development. Good design must balance extra space and glazing with neighbouring outlook, garden depth, roof form and the established rhythm of the street.", "nearbyAreas": ["Edgbaston", "Quinton", "Bartley Green", "Selly Oak", "Moseley", "Birmingham"], "serviceSlugs": ["house-extensions", "loft-conversions", "planning-applications", "building-regulations"], "points": ["Kitchen and family extensions", "Two-storey additions", "Loft conversions", "Planning and technical drawings"]},
  {"slug": "middlesbrough", "title": "Residential Architect Middlesbrough", "shortTitle": "Middlesbrough", "seoTitle": "Residential Architect Middlesbrough | Planning & Building Regulations", "description": "Residential architect in Middlesbrough for extensions, lofts, HMOs, new homes, planning applications and Building Regulations drawings.", "intro": "Hepburn Architects provides residential design, planning and technical services across Middlesbrough and the wider Teesside area.", "localContext": "Middlesbrough projects range from alterations to traditional terraces and suburban family homes to HMOs, conversions and small development sites. We assess the property, planning history, parking, amenity and technical constraints before developing the design.", "nearbyAreas": ["Nunthorpe", "Acklam", "Marton", "Linthorpe", "Stockton-on-Tees", "Yarm"], "serviceSlugs": ["house-extensions", "hmo-conversions", "planning-applications", "building-regulations"], "points": ["House extensions and lofts", "HMOs and residential conversions", "New-build homes", "Planning and Building Regulations"]},
  {"slug": "teesside", "title": "Residential Architect Teesside", "shortTitle": "Teesside", "seoTitle": "Residential Architect Teesside | Extensions, New Homes & Planning", "description": "Residential architect across Teesside for extensions, conversions, new homes, planning applications and Building Regulations drawings.", "intro": "Local architectural expertise for homeowners, developers and investors across Middlesbrough, Stockton, Yarm and surrounding Teesside areas.", "localContext": "Teesside includes varied urban, suburban and semi-rural settings. We tailor the planning strategy and design response to the individual authority, site context, access, neighbour relationships and development potential.", "nearbyAreas": ["Middlesbrough", "Stockton-on-Tees", "Yarm", "Nunthorpe", "Redcar", "Cleveland"], "serviceSlugs": ["house-extensions", "new-build-homes", "planning-applications", "building-regulations"], "points": ["Feasibility and site appraisal", "Planning drawings and statements", "Building Regulations", "Small development consultancy"]},
  {"slug": "edgbaston", "title": "Residential Architect Edgbaston", "shortTitle": "Edgbaston", "seoTitle": "Residential Architect Edgbaston | Period Homes & Extensions", "description": "Residential architect in Edgbaston for period-property extensions, remodelling, planning applications and Building Regulations drawings.", "intro": "Design-led residential architecture for substantial homes, sensitive extensions, remodelling and development opportunities in Edgbaston.", "localContext": "Edgbaston contains many large period properties, mature gardens and conservation-sensitive streets. Proposals often need a careful response to heritage significance, trees, boundary treatments, neighbouring amenity and the scale of the original building.", "nearbyAreas": ["Harborne", "Moseley", "Ladywood", "Selly Oak", "Birmingham City Centre", "Birmingham"], "serviceSlugs": ["house-extensions", "loft-conversions", "planning-applications", "building-regulations"], "points": ["Period-property extensions", "Whole-house remodelling", "Conservation and character", "Planning and technical design"]},
  {"slug": "sutton-coldfield", "title": "Residential Architect Sutton Coldfield", "shortTitle": "Sutton Coldfield", "seoTitle": "Residential Architect Sutton Coldfield | Extensions & New Homes", "description": "Residential architect in Sutton Coldfield for extensions, loft conversions, new homes, planning and Building Regulations drawings.", "intro": "Practical, design-focused architectural support for family homes, larger extensions, remodelling and residential development opportunities in Sutton Coldfield.", "localContext": "Sutton Coldfield has a varied mix of traditional family houses, larger detached homes and development plots. We consider street character, Green Belt where relevant, trees, access, parking and neighbour amenity from the beginning.", "nearbyAreas": ["Four Oaks", "Boldmere", "Wylde Green", "Streetly", "Mere Green", "Birmingham"], "serviceSlugs": ["house-extensions", "loft-conversions", "new-build-homes", "planning-applications"], "points": ["Single and two-storey extensions", "Loft conversions", "New homes and replacement dwellings", "Planning strategy"]},
  {"slug": "nunthorpe", "title": "Residential Architect Nunthorpe", "shortTitle": "Nunthorpe", "seoTitle": "Residential Architect Nunthorpe | Local Planning & Design", "description": "Residential architect in Nunthorpe for house extensions, new homes, planning applications and Building Regulations drawings.", "intro": "Director-led residential architecture from our Nunthorpe office, supporting homeowners and developers across Nunthorpe, Middlesbrough and surrounding areas.", "localContext": "Nunthorpe includes established suburban homes, character properties and sites near the edge of the settlement. Projects need to respond to local character, landscape, access, neighbour amenity and any countryside or Green Wedge constraints.", "nearbyAreas": ["Marton", "Coulby Newham", "Middlesbrough", "Stokesley", "Great Ayton", "Yarm"], "serviceSlugs": ["house-extensions", "new-build-homes", "planning-applications", "building-regulations"], "points": ["House extensions and remodelling", "New-build and replacement homes", "Planning applications", "Building Regulations"]},
  {"slug": "stockton-on-tees", "title": "Residential Architect Stockton-on-Tees", "shortTitle": "Stockton-on-Tees", "seoTitle": "Residential Architect Stockton-on-Tees | Extensions & Planning", "description": "Residential architect in Stockton-on-Tees for extensions, conversions, HMOs, new homes, planning and technical drawings.", "intro": "Architectural support for homeowners, developers and investors across Stockton-on-Tees and surrounding Teesside communities.", "localContext": "Stockton-on-Tees includes traditional urban housing, suburban estates, village settings and development land. We test planning policy, access, parking, amenity and technical constraints before committing to a design route.", "nearbyAreas": ["Yarm", "Norton", "Ingleby Barwick", "Billingham", "Middlesbrough", "Teesside"], "serviceSlugs": ["house-extensions", "hmo-conversions", "new-build-homes", "planning-applications"], "points": ["Extensions and lofts", "HMOs and conversions", "New homes and small sites", "Planning and technical drawings"]},
  {"slug": "yarm", "title": "Residential Architect Yarm", "shortTitle": "Yarm", "seoTitle": "Residential Architect Yarm | House Extensions & New Homes", "description": "Residential architect in Yarm for house extensions, whole-house remodelling, new homes, planning and Building Regulations drawings.", "intro": "Context-sensitive residential architecture for family homes, character properties and development opportunities across Yarm and the surrounding area.", "localContext": "Yarm combines historic character, established residential streets and newer family housing. Proposals should respond to the original property, garden setting, conservation considerations where relevant and the relationship with neighbouring homes.", "nearbyAreas": ["Eaglescliffe", "Ingleby Barwick", "Stockton-on-Tees", "Stokesley", "Nunthorpe", "Teesside"], "serviceSlugs": ["house-extensions", "new-build-homes", "planning-applications", "building-regulations"], "points": ["House extensions", "Whole-house remodelling", "New-build homes", "Planning and Building Regulations"]},
];


export const guides: PageItem[] = [
  { slug:"planning-permission-house-extension", title:"Do I Need Planning Permission for a House Extension?", shortTitle:"Extension planning permission", description:"A practical guide to planning permission and permitted development for single and two-storey house extensions in England.", intro:"Understand when planning permission is required, when permitted development may apply and which design issues often lead to objections.", points:["Permitted development limits","Neighbour amenity and the 45-degree rule","Character, scale and materials","Application drawings and validation"] },
  { slug:"single-storey-extension-rules", title:"Single-Storey Extension Planning Rules", shortTitle:"Single-storey extension rules", description:"Key permitted development and planning rules for rear, side and wrap-around single-storey extensions.", intro:"A clear guide to depth, height, boundaries, materials, prior approval and common planning pitfalls.", points:["Rear extension depth","Eaves and overall height","Side extensions and width","Larger Home Extension prior approval"] },
  { slug:"two-storey-extension-rules", title:"Two-Storey Extension Planning Rules", shortTitle:"Two-storey extension rules", description:"Planning considerations for two-storey side and rear extensions, including amenity and street character.", intro:"Two-storey additions require careful handling of scale, separation, overlooking and the relationship with neighbouring windows.", points:["45-degree guidance","Side-space and terracing concerns","Roof form and subordinate design","Overlooking and privacy"] },
  { slug:"loft-conversion-planning-permission", title:"Loft Conversion Planning Permission", shortTitle:"Loft conversion planning", description:"When loft conversions need planning permission and how permitted development rules apply.", intro:"A practical overview of dormers, hip-to-gable works, roof volume limits and common planning constraints.", points:["40m³ and 50m³ volume limits","Front roof slopes","Conservation areas and Article 4","Lawful Development Certificates"] },
  { slug:"architect-fees-residential-project", title:"How Much Does an Architect Cost for a Residential Project?", shortTitle:"Residential architect fees", description:"How residential architect fees are structured for surveys, planning applications and Building Regulations.", intro:"Understand fixed fees, staged appointments, exclusions and the consultant costs that may sit outside the architect's fee.", points:["Measured survey fees","Design and planning fees","Building Regulations fees","Third-party costs and VAT"] },
  { slug:"building-regulations-drawings", title:"Building Regulations Drawings Explained", shortTitle:"Building Regulations drawings", description:"What Building Regulations drawings include and why they matter before construction.", intro:"Technical drawings turn a planning design into a coordinated construction proposal for Building Control and contractors.", points:["Structure and foundations","Fire safety","Thermal performance","Drainage and ventilation"] },
  { slug:"hmo-conversion-planning-guide", title:"House to HMO Conversion Planning Guide", shortTitle:"HMO planning guide", description:"Planning, licensing, space standards and fire-safety considerations when converting a house into an HMO.", intro:"The route depends on occupancy, local Article 4 controls, licensing requirements and the physical suitability of the property.", points:["C3 to C4 and sui generis uses","Article 4 Directions","Room and amenity standards","Fire safety and licensing"] },
  { slug:"convert-house-into-flats", title:"Converting a House into Flats: Planning and Building Regulations", shortTitle:"House-to-flats conversion", description:"A guide to planning permission, space standards, sound insulation and fire separation for flat conversions.", intro:"Subdivision into flats is a material change of use and normally requires full planning permission alongside detailed technical coordination.", points:["Principle of conversion","Nationally Described Space Standard","Acoustic separation","Fire strategy and escape"] },
  { slug:"garden-room-planning-permission", title:"Does a Garden Room Need Planning Permission?", shortTitle:"Garden room planning", description:"Permitted development rules for garden offices, studios, gyms and residential outbuildings.", intro:"Many garden rooms can be permitted development, but height, siting, use and designated land restrictions matter.", points:["Incidental use","Boundary height limits","Listed buildings and conservation areas","Building Regulations triggers"] },
  { slug:"lawful-development-certificate", title:"Lawful Development Certificates Explained", shortTitle:"Lawful Development Certificates", description:"When to apply for a Lawful Development Certificate for proposed or existing residential works.", intro:"A certificate provides formal confirmation that a proposal or existing use is lawful under planning legislation.", points:["Proposed versus existing use","Evidence required","Permitted development compliance","Why certificates help on resale"] },
  { slug:"planning-refusal-next-steps", title:"Planning Application Refused: What Should You Do Next?", shortTitle:"After a planning refusal", description:"Options after a residential planning refusal, including amendments, resubmission and appeal.", intro:"A refusal should be reviewed against the officer report, decision notice, development plan and realistic prospects of overcoming each reason.", points:["Understanding refusal reasons","Negotiated redesign","Resubmission strategy","Appeal prospects and timescales"] },
  { slug:"replacement-dwelling-planning", title:"Planning Permission for a Replacement Dwelling", shortTitle:"Replacement dwelling planning", description:"Key planning considerations when replacing an existing house with a new dwelling.", intro:"Replacement homes are assessed against scale, siting, character, countryside policy, access, ecology and sometimes Green Belt tests.", points:["Principle of replacement","Volume and scale","Landscape and ecology","CIL and demolition timing"] },
  { slug:"planning-application-timescales", title:"How Long Does Planning Permission Take?", shortTitle:"Planning timescales", description:"Typical planning application timescales and the factors that can delay residential decisions.", intro:"Most householder applications target an eight-week determination period, although validation, consultation and amendments can extend the programme.", points:["Validation period","Consultation","Officer assessment","Extensions of time"] },
  { slug:"planning-vs-building-regulations", title:"Planning Permission vs Building Regulations", shortTitle:"Planning vs Building Regulations", description:"The difference between planning permission and Building Regulations approval for residential work.", intro:"Planning controls the use and external impact of development; Building Regulations govern health, safety, accessibility and technical performance.", points:["What planning assesses","What Building Control assesses","When both are required","Why drawings differ"] },
  { slug:"house-extension-cost-uk", title:"How Much Does a House Extension Cost in the UK?", shortTitle:"House extension costs", description:"Key factors affecting extension construction costs, professional fees, VAT and contingency allowances.", intro:"Extension costs vary with size, specification, structure, glazing, access and location. Early budgeting should use realistic ranges rather than a single headline figure.", points:["Cost per square metre","Professional and authority fees","Specification and structural complexity","Contingency and inflation"] },
  { slug:"rear-extension-design-ideas", title:"Rear Extension Design Ideas for UK Homes", shortTitle:"Rear extension design ideas", description:"Practical rear extension ideas for light, layout, glazing, materials and garden connection.", intro:"The strongest rear extensions improve movement and daylight as well as adding floor area.", points:["Kitchen and dining layouts","Rooflights and glazing","Material transitions","Garden thresholds"] },
  { slug:"wraparound-extension-planning", title:"Wrap-Around Extension Planning Guide", shortTitle:"Wrap-around extension planning", description:"Planning and design considerations for combined side and rear wrap-around extensions.", intro:"Wrap-around extensions can transform a ground floor but often exceed permitted development limits and require careful planning design.", points:["Planning permission","Subordinate appearance","Neighbour amenity","Roof form and drainage"] },
  { slug:"side-extension-planning-rules", title:"Side Extension Planning Rules", shortTitle:"Side extension rules", description:"Permitted development and planning considerations for side extensions to detached and semi-detached homes.", intro:"Side extensions are sensitive because they can close important gaps, create terracing effects and alter the street scene.", points:["Width and height limits","Setbacks and roof form","Corner plots","Character and spacing"] },
  { slug:"architect-for-planning-permission", title:"Do I Need an Architect for Planning Permission?", shortTitle:"Architect for planning permission", description:"When an architect adds value to a residential planning application and what information is normally required.", intro:"An architect is not legally required for most planning applications, but good design and a robust submission can significantly reduce avoidable risk.", points:["When simple drawings may be enough","Planning-led design","Supporting statements","Complex or sensitive sites"] },
  { slug:"planning-application-validation-checklist", title:"Residential Planning Application Validation Checklist", shortTitle:"Planning validation checklist", description:"Common drawings, forms, reports and information needed to validate a residential planning application.", intro:"A planning application cannot enter formal assessment until the authority confirms it is valid.", points:["Application forms and ownership","Location and site plans","Existing and proposed drawings","Specialist reports"] },
  { slug:"planning-conditions-discharge-guide", title:"How to Discharge Planning Conditions", shortTitle:"Discharging planning conditions", description:"A practical guide to pre-commencement conditions, approval of details and condition discharge applications.", intro:"Conditions can control materials, drainage, ecology, landscaping, noise and construction methods after planning permission is granted.", points:["Pre-commencement conditions","Required evidence","Partial discharge","Timing and implementation"] },
  { slug:"permitted-development-rights-explained", title:"Permitted Development Rights Explained", shortTitle:"Permitted development explained", description:"How permitted development rights work for extensions, lofts, outbuildings and residential alterations.", intro:"Permitted development is a national planning permission subject to detailed limitations, conditions and local restrictions.", points:["What permitted development covers","Article 4 Directions","Previous extensions","Lawful Development Certificates"] },
  { slug:"planning-permission-conservation-area", title:"Planning Permission in a Conservation Area", shortTitle:"Conservation area planning", description:"Design and planning considerations for residential work in conservation areas.", intro:"Conservation-area status does not prevent change, but it places greater emphasis on character, materials, views and local distinctiveness.", points:["Character appraisal","Permitted development restrictions","Materials and detailing","Heritage statements"] },
  { slug:"listed-building-extension-guide", title:"Extending a Listed Building", shortTitle:"Listed building extensions", description:"Planning permission, listed building consent and design principles for extending a listed property.", intro:"Work to a listed building requires a clear understanding of significance and a design that avoids or justifies harm.", points:["Listed building consent","Heritage significance","Reversible design","Specialist surveys"] }

];

export function findPage(items: PageItem[], slug: string) {
  return items.find((item) => item.slug === slug);
}
